# Generated by Django 3.0.3 on 2020-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Book Title')),
                ('author', models.CharField(max_length=120, verbose_name='Book Author')),
                ('genre', models.CharField(choices=[('nonfiction', 'NONFICTION'), ('fiction', 'FICTION'), ('narrative', 'NARRATIVE'), ('science fiction', 'SCIENCE FICTION'), ('romance', 'ROMANCE'), ('history', 'HISTORY'), ('fantasy', 'FANTASY'), ('educational', 'EDUCATIONAL'), ('thriller', 'THRILLER'), ('children', 'CHILDREN')], default='nonfiction', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BookAdded',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(default='Default', max_length=120, verbose_name='Book Title')),
                ('user', models.CharField(default='Default', max_length=120, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review_desc', models.TextField()),
            ],
        ),
    ]
