# Generated by Django 3.0.3 on 2020-02-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200211_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookadded',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookadded',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bookadded',
            name='book_title',
            field=models.CharField(default='Default', max_length=120, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='bookadded',
            name='user',
            field=models.CharField(default='Default', max_length=120, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='bookadded',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
