# Generated by Django 3.0.3 on 2020-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200212_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='review_desc',
            field=models.TextField(default='-no description entered-'),
        ),
    ]
