# Generated by Django 3.0.3 on 2020-02-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200213_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review_desc',
            field=models.TextField(default='-- no description --'),
        ),
    ]
